name: Build Raspberry Application

on:
  push:
    paths:
      - 'src/Sting.Measurements/**'
      - 'src/Sting.Backend/**'

jobs:

  Build-Raspi:
    name: Build Raspberry Application
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      - name: Build Sting.Application
        run: dotnet build --configuration Release src/Sting.Measurements/Sting.Application
      - name: Build Sting.Core
        run: dotnet build --configuration Release src/Sting.Measurements/Sting.Core
      - name: Build Sting.Devices
        run: dotnet build --configuration Release src/Sting.Measurements/Sting.Devices
